export class User {
  /**
   * 사용자 아이디 (autogenerated PK)
   */
  id: number;

  /**
   * 사용자 이름
   */
  name: string;

  /**
   * 로그인 아이디 (unique)
   */
  loginId: string;

  /**
   * 비밀번호
   */
  password: string;
}
